name: CI/CD workflow for Node.js Build and Sonar Code scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl -f http://localhost:9000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    # Comment out or remove this step if you don't have tests
    # - name: Run tests
    #   run: npm test

    - name: Wait for SonarQube to be ready
      run: |
        echo "Waiting for SonarQube to be ready..."
        while ! curl -s http://localhost:9000; do sleep 5; done

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=my-org
          -Dsonar.projectKey=my-nodejs-project
          -Dsonar.host.url=http://localhost:9000
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
